---
# task file for wildfly

- name: Install OpenJDK
  yum:
    name: java-1.8.0-openjdk-headless
    state: present
  when: wildfly_manage_java_pkg

- name: Download wildfly tar file
  get_url:
    url: '{{ wildfly_download_url }}'
    dest: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    validate_certs: '{{ wildfly_download_validate_certs }}'

- block:
    - name: Create wildfly group
      group:
        name: '{{ wildfly_group }}'
        state: present

    - name: Create wildfly user
      user:
        name: '{{ wildfly_user }}'
        group: '{{ wildfly_group }}'
        createhome: no
        shell: "{{ wildfly_user_shell |default(omit) }}"
        state: present
  when: wildfly_manage_user

- name: Unarchive downloaded file
  unarchive:
    src: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    dest: '{{ wildfly_install_dir }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    copy: no
    creates: "{{ wildfly_dir }}/bin/standalone.sh"

- name: Create symlink to installed version
  file:
    state: link
    src: "{{ wildfly_dir }}"
    dest: "{{ wildfly_install_dir }}/wildfly"
  when: wildfly_create_symlink
