---
# tasks file for wildfly

# This status will always be "changed" unless skipped because it will update
# if exists even with the same credentials.
- name: Create management user
  command: >
    {{ wildfly_dir }}/bin/add-user.sh
    {{ wildfly_management_user }} {{ wildfly_management_password }}
  sudo_user: wildfly
  when: wildfly_management_user is defined and
        wildfly_management_password is defined and
        wildfly_management_user_overwrite
